spring:
  application:
    name: HearthLogs Server
security:
  oauth2:
    client:
      client-id: 4q8t6js62qp7m8unpjjfn8phph5xhemt
      client-secret: PTywt4SWSv63EAKGhCyHumVc9dVuXQcw
      access-token-uri: https://us.battle.net/oauth/token
      user-authorization-uri: https://us.battle.net/oauth/authorize
multipart.maxFileSize: 10MB
server.port: 8443
server.ssl.key-store: classpath:keystore.p12
server.ssl.key-store-password: 4me2know
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat