spring:
  application:
    name: HearthLogs Server
  datasource:
    url: jdbc:postgresql://127.0.0.1:9001/hearthlogs
    username: hl
    password: STP*,96w
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    solr:
      host: http://127.0.0.1:9000/solr/hearthlogs
security:
  oauth2:
    client:
      client-id: 4q8t6js62qp7m8unpjjfn8phph5xhemt
      client-secret: PTywt4SWSv63EAKGhCyHumVc9dVuXQcw
      access-token-uri: https://us.battle.net/oauth/token
      user-authorization-uri: https://us.battle.net/oauth/authorize