spring:
  application:
    name: HearthLogs Server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
security:
  oauth2:
    client:
      client-id: 4q8t6js62qp7m8unpjjfn8phph5xhemt
      client-secret: PTywt4SWSv63EAKGhCyHumVc9dVuXQcw
      access-token-uri: https://us.battle.net/oauth/token
      user-authorization-uri: https://us.battle.net/oauth/authorize
multipart.maxFileSize: 10MB