spring:
  mvc:
    favicon:
      enabled: false
  application:
    name: HearthGames Server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hearthgames
    username: hl
    password: fuckmi69
security:
  oauth2:
    client:
      client-id: 67a2qaet3tenu4xa3jrdhrbegr3ncthv
      client-secret: KX48ftbpuTEPjrXxZQuzPhfv4rP7yKak
      access-token-uri: https://us.battle.net/oauth/token
      user-authorization-uri: https://us.battle.net/oauth/authorize
      pre-established-redirect-uri: https://hearthgames.com/login
      use-current-uri: false
multipart.maxFileSize: 100MB
multipart.maxRequestSize: 100MB
hearthgames.redirect-url: http://hearthgames.com/dashboard
---
spring.profiles: dev
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/hearthgames
    username: hl
    password: fuckmi69
#spring.jpa.hibernate.ddl-auto: create
security:
  oauth2:
    client:
      client-id: kawuekf38hed2qdn9e3wsevkzdbam8a9
      client-secret: SZKWwBYwtjMhgHP9qWmeAuq73seF3QRT
      pre-established-redirect-uri: https://localhost:8443/login
server.port: 8443
server.ssl.key-store: classpath:keystore.p12
server.ssl.key-store-password: 4me2know
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat
hearthgames.redirect-url: https://localhost:8443/dashboard